### ISSUE TITLE
UI doesn't show progress or completion

### ISSUE THREAD

**Issue by dratzinger** [hkdb/Densify#8] opened 2021-03-13 15:00 UTC
After starting the compression via the button, the status changes to "Compressing..." and the status bar bounces back and forth. The bar does not update while processing. When the compression is done, there is no change in status - only closing and reopening the application resets the status. This also means, only one file can be compressed per start.

![compressing](https://user-images.githubusercontent.com/26470120/111033791-38601c80-8413-11eb-95bc-7e985a53188b.gif)

I am using the [v0.3.1](https://github.com/hkdb/Densify/releases/tag/v0.3.1) AppImage.

**Comment by jose1711** [comment] 2023-03-05 23:48
For me the status changes to "Completed". Could you possibly share the input file?

**Comment by hkdb** [comment] 2024-06-24 10:07
Unless you do not have ghostscript installed. this could be also caused by #9 which is resolved in v0.3.2. Please open a new issue if this is not the case. Thanks!

**Closed as completed by hkdb** 2024-06-24 10:07 UTC
